/**
 * Created by abaddon on 3/21/23.
 */

import * as h from "c/helpersLWC";

export const flattenObject = h.flattenObject;
export const sortFlatList = h.sortFlatList;
export const searchFlatList = h.searchFlatList;
export const betweenTwoDates = h.betweenTwoDates;

export const columns = [
    {
        label: "Test",
        fieldName: "test",
        type: "button",
        sortable: true,
        initialWidth: 150,
        typeAttributes: {
            label: { fieldName: "test" },
            title: "Click to View Lab Details",
            name: "testClicked",
            variant: "base",
            type: "text"
        },
        wrapText: false,
        cellAttributes: {
            style: "padding: 0 !important; flex-wrap: nowrap !important",
            class: "slds-has-flexi-truncate"
        }
    },
    {
        label: "Date",
        fieldName: "collectedDate",
        type: "date",
        sortable: true,
        typeAttributes: {
            weekday: "short",
            year: "numeric",
            month: "short",
            day: "2-digit",
            timeZone: "UTC"
        }
    },
    { label: "Result", fieldName: "result", type: "text", sortable: true },
    { label: "Status", fieldName: "status", type: "text", sortable: true },
    { label: "Sample", fieldName: "sample", type: "text", sortable: true },
    { label: "Providers", fieldName: "provider", type: "text", sortable: true }
];
export const labReference = [
    { test: "SLT" },
    { test: "UREA NITROGEN" },
    { test: "CREATININE" },
    { test: "eGFR (IDMS)" },
    { test: "SODIUM" },
    { test: "POTASSIUM" },
    { test: "CHLORIDE" },
    { test: "CARBON DIOXIDE CONTENT" },
    { test: "CALCIUM" },
    { test: "ALBUMIN" },
    { test: "CALCIUM, CORRECTED" }
];
export const mainRef = [{ review: "main" }, { review: "main" }, { review: "main" }, { review: "main" }];
export const paxRef = [
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "legal" },
    { review: "main" },
    { review: "main" },
    { review: "legal" },
    { review: "medications" },
    { review: "medications" },
    { review: "medications" },
    { review: "medications" },
    { review: "medications" },
    { review: "medications" },
    { review: "medications" },
    { review: "contraindications" },
    { review: "medications" },
    { review: "medications" },
    { review: "labs" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "dosage" },
    { review: "disposition" },
    { review: "disposition" },
    { review: "disposition" },
    { review: "disposition" }
];
export const molRef = [
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "main" },
    { review: "legal" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "criteria" },
    { review: "childbearing" },
    { review: "childbearing" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "pregnant" },
    { review: "dosage" },
    { review: "disposition" },
    { review: "disposition" },
    { review: "disposition" },
    { review: "disposition" },
    { review: "disposition" }
];

export const apiNames = [
    { apiName: "PostiveCovideTestDispTxt", index: 0 },
    { apiName: "Assess_Covid_test", index: 1 },
    { apiName: "TreatmentDiscTxt", index: 2 },
    { apiName: "Select_a_treatment", index: 3 },
    { apiName: "patientInterestedInPaxlovid", index: 4 },
    { apiName: "paxConsentDisplayText", index: 5 },
    { apiName: "paxCounseledDisplayText", index: 6 },
    { apiName: "limitationofEUADisplayText", index: 7 },
    { apiName: "Would_you_like_to_consider_Molnupiravir", index: 8 },
    { apiName: "paxNotConsideredDisplayText", index: 9 },
    { apiName: "Paxlovid_Message", index: 10 },
    { apiName: "vccAllergyTestToTreat", index: 11 },
    { apiName: "vcc_Hypersensitivity_Choice_Radio", index: 12 },
    { apiName: "vcc_CovidTest2Treat_Prescriptions", index: 13 },
    { apiName: "VCC_Medication_Reconciliation_Options__c", index: 14 },
    { apiName: "VCC_Medication_Reconciliation_Options_Rn__c", index: 15 },
    { apiName: "VCC_T2T_Medication_Discrepancies_Additional_Info", index: 16 },
    { apiName: "VCC_Display_Text_Choice", index: 17 },
    { apiName: "VCC_T2T_Contraindications_Display", index: 18 },
    { apiName: "VCC_T2T_Drug_Interactions_Picklist", index: 19 },
    { apiName: "VCC_Medication_Education__c", index: 20 },
    { apiName: "VCC_T2T_Medication_Education_Additional_Info", index: 21 },
    { apiName: "VCCAllergyT2TLabs", index: 22 },
    { apiName: "VCC_T2T_Test_Confirmed_Text", index: 23 },
    { apiName: "VCC_T2T_No_Hospitalization_Text", index: 24 },
    { apiName: "VCC_T2T_Symptom_Onset_Text", index: 25 },
    { apiName: "VCC_T2T_Symptom_Details_Long", index: 26 },
    { apiName: "VCC_T2T_Blurb_Medical_text", index: 27 },
    { apiName: "VCC_T2T_Criteria_Choice_Picklist", index: 28 },
    { apiName: "VCC_T2T_Dosage_Radio", index: 29 },
    { apiName: "PatientandorCaregiverConsentstoPaxlovidUseDisplayTxt", index: 30 },
    { apiName: "patientenrolledinCOVID19followupTreatmentDisplayTxt", index: 31 },
    { apiName: "Medication_adjustments_needed_as_follows", index: 32 },
    { apiName: "Patient_is_denied_due_to_the_following", index: 33 },
    { apiName: "Would_you_like_to_consider_Molnupiravir_disposition", index: 34 },
    { apiName: "Patient_has_a_drug_drug_interaction_that_preclude_Paxlovid_use", index: 35 },
    { apiName: "d_dInteractionPrecludePaxUseReasonText", index: 36 },
    { apiName: "Patient_has_encountered_side_effects_that_preclude_continued_Paxlovid_use", index: 37 },
    { apiName: "encounteredSideEffectsPrecludePaxlovidUseReasonText", index: 38 },
    { apiName: "Patient_has_contraindications_for_Paxlovid_use", index: 39 },
    { apiName: "contradicationsPaxlovidUseReasonText", index: 40 },
    { apiName: "Patient_declines_Paxlovid", index: 41 },
    { apiName: "declinesPaxlovidReasonText", index: 42 },
    { apiName: "molConsentDisplayTxt", index: 43 },
    { apiName: "limitationofEUADisplayTxt", index: 44 },
    { apiName: "Positive_SARS_CoV_2_test", index: 45 },
    { apiName: "Symptoms_onset_within_5_days", index: 46 },
    { apiName: "Symptom_Details", index: 47 },
    { apiName: "consentDisplayText", index: 48 },
    { apiName: "Patient_has_met_ALL_the_above_criteria", index: 49 },
    { apiName: "Was_patient_male_at_birth", index: 50 },
    { apiName: "Report_of_last_menstrual_period", index: 51 },
    { apiName: "Negative_pregnancy_test", index: 52 },
    { apiName: "Pregnant_Patients", index: 53 },
    { apiName: "pregnancyBeneftandRisksDisplayTxt", index: 54 },
    { apiName: "pregnancySurveillanceProgramDisplayTxt", index: 55 },
    { apiName: "PatientAgreestoParticipateinPregnancySurveillanceDisplayTxt", index: 56 },
    { apiName: "PSPAwarenessifBecomePregnantDisplayTxt", index: 57 },
    { apiName: "patientAgreestoParticipateInPSPifPregnantDisplayTxt", index: 58 },
    { apiName: "reviewedContraceptionRequirementsPerMolFactSheetDisplayTxt", index: 59 },
    { apiName: "dosageandAdministrationDisplayText", index: 60 },
    { apiName: "molnupiravirUserConsentDispositionDisplayTxt", index: 61 },
    { apiName: "molnupiravirTreatmentEnrollmentDisplayTxt", index: 62 },
    { apiName: "molnupiravirPatientAdverseReactionReportAwarenessDisplayTxt", index: 63 },
    { apiName: "Request_denied_due_to_the_following", index: 64 },
    { apiName: "Patient_does_not_qualify_currently_for_either_Paxlovid_or_Molnupiravir", index: 65 }
];
