/**
 * Name: BatchJobConstants
 * @author Brenda Finn
 * @date 12/20/21
 * 
 * @description Constants for Batch Job Framework
 *
 * @group Batch Framework
 * @see BatchJobBase
 * @see BatchJobSchedulingMgr
 */
public with sharing class BatchJobConstants {
    public static final String USE_START_DATE = 'Use Start Date';
    public static final String BATCH_JOB_BASE_MOCK_CLASS_NAME = 'BatchJobBaseMock';
    public static final String TEST_JOB_NAME = 'TEST';
    public static final String TEST_AUTOMATION_TYPE = 'Test Automation Type';
}
