name: Generate ApexDocs Deploy To Wiki
# This workflow is triggered on pull requests to release branches.
# The majority of this logic is in the ApexDocWikiManager.ts file, which is compiled to a js file in the steps below.
# Typescript gives us a lot of type safety and allows us to write more maintainable code, but needs to be compiled to run in the github actions environment.
# The 'Compile Typescript' step uses bun to compile the typescript file to a mjs file, which is then imported and run in the 'Generate & Publish ApexDocs' step.
# Please see the <root>./github/workflows/lib/ApexDocWikiManager.mts file for the main logic of this action.
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  generate-apexdocs-to-wiki:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'synchronize' || (github.event.action == 'synchronize' && vars.TESTING_WF_ACTION == 'true') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Compile Typescript
        run: |
          bun build --target node .github/workflows/lib/ApexDocWikiManager.ts --outfile .github/workflows/lib/ApexDocWikiManager.js --format esm

      - uses: actions/github-script@v7
        continue-on-error: true
        name: Generate & Publish ApexDoc
        id: exec
        with:
#          repository: ${{ github.repository }}.wiki
#          token: ${{ secrets.WIKI_PUSH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path')
            const file = '.github/workflows/lib/ApexDocWikiManager.mjs'
            // Import the module (ts file) and generate the ApexDocs
            const apexDocWikiManager = await import('${{ github.workspace }}/.github/workflows/lib/ApexDocWikiManager.mjs');
            if (apexDocWikiManager) {
              console.log('======> generating ApexDoc');
              const wikiRepoToken = '${{ secrets.WIKI_PUSH_TOKEN }}';
              // For some reason, I cannot access the target branch from within the apexDocWikiManager context so passing it in.
              const targetBranch = '${{ github.base_ref}}';
              await apexDocWikiManager.default({github, context, core, wikiRepoToken, targetBranch});
              console.log('=====> results = ${{steps.exec.outputs.result}}');
            } else {
              throw new Error('The module could not be loaded, or does not have a run method')
            }