name: PR Notifier

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  schedule:
    # This runs every 15 minutes between the approximated UTC times for 7:45 AM Eastern and 6:00 PM Pacific.
    # Adjust this based on daylight saving time changes.
    - cron: '0/15 * * * 1-5'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.DEPECHE_CODE_PR_CHANNEL_WEBHOOK_URL }}
  APPROVERSLIST: ${{ vars.APPROVERS_LIST}}

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - name: 'Install dependencies'
        run: npm ci
      - name: Notify Slack via GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            const generateSlackPRNotificationImport = await import('${{ github.workspace }}/.github/workflows/lib/generateSlackPRNotification.mjs');
            const generateSlackPRNotification = generateSlackPRNotificationImport.default;
            const slackUrl = process.env.SLACK_WEBHOOK_URL;
            const approversList = process.env.APPROVERSLIST;
            instance = new generateSlackPRNotification(github, context, slackUrl, approversList);
            await instance.buildAndSendSlackNotificationOfPRStatus();
          
                        
