name: Release Reporting

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Run daily at 10pm UTC

jobs:
  find_branches_without_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Find branches without PRs
        run: |
          git fetch --all
          # Get all the branches in the repository
          branches=$(git branch -r | grep -v HEAD | sed "s/origin\///")
          
          # Loop through each branch and check if it diverged from release/1.11.0
          
          for branch in $branches; do
            echo "Checking branch: $branch"
            # Check if the branch diverged from release/1.11.0
            common_ancestor=$(git merge-base origin/release/1.11.0 origin/$branch)
            echo "%%% Common ancestor: $common_ancestor"
            git branch -a --contains $common_ancestor
            echo "###"
            if git merge-base --is-ancestor origin/release/1.11.0 origin/$branch; then
              # Check if the branch has an open pull request
              pr_url=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:$branch | jq '.[].html_url')
      
              if [ -z "$pr_url" ]; then
                echo "Branch $branch does not have an open pull request"
              fi
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}