name: Check @suppressWarnings Usage

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  check-suppress-warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check @suppressWarnings usage
        uses: actions/github-script@v7
        with:
          script: |
            const { default: SuppressWarningsChecker } = await import('${{ github.workspace }}.github/workflows/lib/suppressWarningsCheck.mjs');
            const checker = new SuppressWarningsChecker(github, context);
            
            let checkPassed = await checker.checkPullRequest();
            
            if (!checkPassed) {
              const reviewResolved = await checker.checkReviewResolution();
              if (!reviewResolved) {
                core.setFailed('@suppressWarnings( found in changed lines. Please provide justification and get approval from Depeche Code team.');
              }
            }